"""Postman collection and environment generator."""

from __future__ import annotations

import json
import logging
import re
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional

from src.agents.generator_registry import GeneratorRegistry
from src.models.execution import ScenarioExecutionResult, VariableContext
from src.models.scenario import ScenarioStabilizationInput, TestStep

logger = logging.getLogger(__name__)

POSTMAN_SCHEMA = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
_VAR_RE = re.compile(r"\{\{\s*(\w+)\s*\}\}")
_DEFAULT_REGISTRY_PATH = Path("data/generator_registry.json")


class PostmanGenerator:
    """Builds Postman v2.1 collections from scenarios or successful execution traces."""

    def __init__(self, registry_path: Path = _DEFAULT_REGISTRY_PATH, reset_mock_between_scenarios: bool = True) -> None:
        self.registry = GeneratorRegistry(registry_path)
        self.reset_mock_between_scenarios = reset_mock_between_scenarios

    def generate(
        self,
        scenarios: List[ScenarioStabilizationInput],
        constants: Dict[str, Any],
        collection_name: str = "Generated API Test Suite",
    ) -> Dict[str, Any]:
        logger.info("PostmanGenerator: building collection from %d scenario card(s)", len(scenarios))
        return {
            "info": self._info(collection_name),
            "item": [self._scenario_folder(scenario) for scenario in scenarios],
            "variable": self._variables_from_constants(constants),
        }

    def generate_from_execution(
        self,
        result: ScenarioExecutionResult,
        collection_name: Optional[str] = None,
    ) -> Dict[str, Any]:
        logger.info("PostmanGenerator: building collection from execution result %s", result.scenario_name)
        name = collection_name or result.scenario_name
        return {
            "info": self._info(name),
            "item": [
                {
                    "name": result.scenario_name,
                    "description": "\n".join(result.reasoning_log),
                    "item": [self._executed_item(request) for request in result.ready_requests],
                }
            ],
            "variable": self._variables_from_context(result.variables),
        }

    def generate_environment(
        self,
        variables: VariableContext,
        environment_name: str = "Generated API Test Environment",
    ) -> Dict[str, Any]:
        values = variables.values()
        return {
            "id": str(uuid.uuid4()),
            "name": environment_name,
            "values": [
                {"key": key, "value": self._stringify(value), "type": "default", "enabled": True}
                for key, value in sorted(values.items())
            ],
            "_postman_variable_scope": "environment",
            "_postman_exported_using": "TestDesignerAI",
        }

    @staticmethod
    def _info(name: str) -> Dict[str, Any]:
        return {
            "_postman_id": str(uuid.uuid4()),
            "name": name,
            "schema": POSTMAN_SCHEMA,
            "description": "Generated by TestDesignerAI multi-agent pipeline.",
        }

    def _scenario_folder(self, scenario: ScenarioStabilizationInput) -> Dict[str, Any]:
        items = []
        if self.reset_mock_between_scenarios:
            items.append(self._reset_item())
        items.extend(self._scenario_item(step) for step in scenario.steps)
        return {
            "name": scenario.scenario_name,
            "description": scenario.business_context,
            "item": items,
        }

    def _scenario_item(self, step: TestStep) -> Dict[str, Any]:
        return {
            "name": f"Step {step.step}: {step.name}",
            "request": self._request_object(
                method=step.method,
                path=self._template_path(step),
                headers=step.headers,
                query=step.query_params,
                body=step.request_body,
                description=step.description or "\n".join(step.success_criteria),
            ),
            "event": [
                {"listen": "prerequest", "script": {"type": "text/javascript", "exec": self._pre_request_lines(step)}},
                {"listen": "test", "script": {"type": "text/javascript", "exec": self._test_lines(step)}},
            ],
            "response": [],
        }

    def _executed_item(self, request) -> Dict[str, Any]:
        return {
            "name": f"Step {request.step}: {request.name}",
            "request": self._request_object(
                method=request.method,
                path=request.templated_path,
                headers=request.templated_headers,
                query=request.templated_query_params,
                body=request.templated_request_body,
                description=f"Successful response example: {json.dumps(request.response_body, ensure_ascii=False)}",
            ),
            "response": [
                {
                    "name": "Successful response",
                    "originalRequest": self._request_object(
                        method=request.method,
                        path=request.templated_path,
                        headers=request.templated_headers,
                        query=request.templated_query_params,
                        body=request.templated_request_body,
                    ),
                    "status": str(request.response_status),
                    "code": request.response_status,
                    "body": json.dumps(request.response_body, ensure_ascii=False, indent=2),
                    "header": [{"key": "Content-Type", "value": "application/json"}],
                }
            ],
            "event": [
                {
                    "listen": "test",
                    "script": {
                        "type": "text/javascript",
                        "exec": [f"pm.response.to.have.status({request.response_status});"],
                    },
                }
            ],
        }

    def _request_object(
        self,
        method: str,
        path: str,
        headers: Optional[Dict[str, Any]],
        query: Optional[Dict[str, Any]],
        body: Optional[Any],
        description: Optional[str] = None,
    ) -> Dict[str, Any]:
        raw = "{{base_url}}" + path
        query_items = []
        if query:
            query_items = [{"key": key, "value": self._stringify(value)} for key, value in query.items()]
            raw += "?" + "&".join(f"{item['key']}={item['value']}" for item in query_items)
        request: Dict[str, Any] = {
            "method": method,
            "header": [{"key": key, "value": self._stringify(value)} for key, value in (headers or {}).items()],
            "url": {
                "raw": raw,
                "host": ["{{base_url}}"],
                "path": [segment for segment in path.strip("/").split("/") if segment],
            },
        }
        if query_items:
            request["url"]["query"] = query_items
        if body is not None:
            request["body"] = {
                "mode": "raw",
                "raw": json.dumps(body, ensure_ascii=False, indent=2),
                "options": {"raw": {"language": "json"}},
            }
        if description:
            request["description"] = description
        return request

    @staticmethod
    def _template_path(step: TestStep) -> str:
        path = step.path
        for name, value in step.path_params.items():
            path = path.replace(f"{{{name}}}", str(value))
        return path

    def _pre_request_lines(self, step: TestStep) -> List[str]:
        lines: List[str] = []
        refs = self._refs([step.path, step.path_params, step.headers, step.query_params, step.request_body])
        for name in sorted(refs):
            func = self.registry.lookup(name)
            if func and func.js_snippet:
                lines.extend(func.js_snippet.splitlines())
                lines.append("")
        return lines

    def _test_lines(self, step: TestStep) -> List[str]:
        lines = [
            f'pm.test("HTTP status is {step.expected_status}", function () {{',
            f"  pm.response.to.have.status({step.expected_status});",
            "});",
            "",
        ]
        if step.extract_variables or step.assertions:
            lines.extend(["const json = pm.response.json();", ""])
        for rule in step.extract_variables:
            js_expr = self._jsonpath_to_js(rule.expression)
            lines.extend(
                [
                    f"const {rule.name} = {js_expr};",
                    f"if ({rule.name} !== undefined && {rule.name} !== null) {{",
                    f'  pm.collectionVariables.set("{rule.name}", {rule.name});',
                    "}",
                    "",
                ]
            )
        for assertion in step.assertions:
            js_expr = self._jsonpath_to_js(assertion.path)
            expected = json.dumps(assertion.expected, ensure_ascii=False)
            lines.append(f'pm.test("{assertion.description}", function () {{')
            if assertion.operator == "not_null":
                lines.append(f"  pm.expect({js_expr}).to.not.be.null;")
                lines.append(f"  pm.expect({js_expr}).to.not.be.undefined;")
            elif assertion.operator == "exists":
                lines.append(f"  pm.expect({js_expr}).to.not.equal(undefined);")
            elif assertion.operator == "eq":
                lines.append(f"  pm.expect(String({js_expr})).to.equal(String({expected}));")
            elif assertion.operator == "ne":
                lines.append(f"  pm.expect(String({js_expr})).to.not.equal(String({expected}));")
            elif assertion.operator == "contains":
                lines.append(f"  pm.expect({js_expr}).to.include({expected});")
            else:
                lines.append("  pm.expect(true).to.equal(true);")
            lines.extend(["});", ""])
        return lines

    @staticmethod
    def _jsonpath_to_js(path: str) -> str:
        if path == "$":
            return "json"
        if path.startswith("$."):
            return "json." + path[2:]
        if path.startswith("$["):
            return "json" + path[1:]
        return "json." + path.lstrip("$.")

    @staticmethod
    def _variables_from_constants(constants: Dict[str, Any]) -> List[Dict[str, Any]]:
        return [{"key": key, "value": PostmanGenerator._stringify(value), "type": "any"} for key, value in sorted(constants.items())]

    @staticmethod
    def _variables_from_context(context: VariableContext) -> List[Dict[str, Any]]:
        return [
            {"key": key, "value": PostmanGenerator._stringify(value), "type": "any"}
            for key, value in sorted(context.values().items())
        ]

    @staticmethod
    def _refs(values: List[Any]) -> set[str]:
        refs: set[str] = set()

        def visit(value: Any) -> None:
            if isinstance(value, str):
                refs.update(_VAR_RE.findall(value))
            elif isinstance(value, dict):
                for item in value.values():
                    visit(item)
            elif isinstance(value, list):
                for item in value:
                    visit(item)

        for value in values:
            visit(value)
        return refs

    @staticmethod
    def _stringify(value: Any) -> str:
        if isinstance(value, (dict, list)):
            return json.dumps(value, ensure_ascii=False)
        return "" if value is None else str(value)

    @staticmethod
    def _reset_item() -> Dict[str, Any]:
        return {
            "name": "Setup: Reset Mock Server",
            "request": {
                "method": "POST",
                "header": [{"key": "Accept", "value": "application/json"}],
                "url": {
                    "raw": "{{base_url}}/v1/debug/reset",
                    "host": ["{{base_url}}"],
                    "path": ["v1", "debug", "reset"],
                },
            },
            "event": [
                {
                    "listen": "test",
                    "script": {
                        "type": "text/javascript",
                        "exec": ["pm.response.to.have.status(200);"],
                    },
                }
            ],
            "response": [],
        }
